package ventas.vistas;

/**
 *
 * @author Fede
 */
public class VistaElegirMedioDePago extends javax.swing.JFrame {


    public VistaElegirMedioDePago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        botonesMetodoDePago = new javax.swing.ButtonGroup();
        panelSuperior = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        rbEfectivo = new javax.swing.JRadioButton();
        rbDebito = new javax.swing.JRadioButton();
        rbCredito = new javax.swing.JRadioButton();
        campoTotal = new javax.swing.JTextField();
        tituloTotal = new javax.swing.JLabel();
        cbCuotas = new javax.swing.JComboBox<>();
        tituloCuotas = new javax.swing.JLabel();
        tituloValorCuotas = new javax.swing.JLabel();
        campoValorCuota = new javax.swing.JTextField();
        tituloInteres = new javax.swing.JLabel();
        campoInteres = new javax.swing.JTextField();
        panelInferior = new javax.swing.JPanel();
        botonConfirmar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titulo.setText("Elige el método de pago");
        panelSuperior.add(titulo);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setLayout(new java.awt.GridBagLayout());

        botonesMetodoDePago.add(rbEfectivo);
        rbEfectivo.setText("Efectivo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelCentral.add(rbEfectivo, gridBagConstraints);

        botonesMetodoDePago.add(rbDebito);
        rbDebito.setText("Débito");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        panelCentral.add(rbDebito, gridBagConstraints);

        botonesMetodoDePago.add(rbCredito);
        rbCredito.setText("Crédito");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 64);
        panelCentral.add(rbCredito, gridBagConstraints);

        campoTotal.setEnabled(false);
        campoTotal.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(21, 11, 25, 11);
        panelCentral.add(campoTotal, gridBagConstraints);

        tituloTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloTotal.setText("Total");
        tituloTotal.setMinimumSize(new java.awt.Dimension(40, 30));
        tituloTotal.setPreferredSize(new java.awt.Dimension(40, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(21, 11, 25, 20);
        panelCentral.add(tituloTotal, gridBagConstraints);

        cbCuotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2", "3", "6", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 17, 0);
        panelCentral.add(cbCuotas, gridBagConstraints);

        tituloCuotas.setText("Cantidad de cuotas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(17, 12, 17, 0);
        panelCentral.add(tituloCuotas, gridBagConstraints);

        tituloValorCuotas.setText("Valor por cada cuota");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 17, 0);
        panelCentral.add(tituloValorCuotas, gridBagConstraints);

        campoValorCuota.setEnabled(false);
        campoValorCuota.setPreferredSize(new java.awt.Dimension(80, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 17, 0);
        panelCentral.add(campoValorCuota, gridBagConstraints);

        tituloInteres.setText("Interés");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 17, 0);
        panelCentral.add(tituloInteres, gridBagConstraints);

        campoInteres.setEnabled(false);
        campoInteres.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.insets = new java.awt.Insets(17, 10, 17, 10);
        panelCentral.add(campoInteres, gridBagConstraints);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        botonConfirmar.setText("Confirmar venta");
        panelInferior.add(botonConfirmar);

        botonCancelar.setText("Cancelar");
        panelInferior.add(botonCancelar);

        getContentPane().add(panelInferior, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.ButtonGroup botonesMetodoDePago;
    private javax.swing.JTextField campoInteres;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JTextField campoValorCuota;
    private javax.swing.JComboBox<String> cbCuotas;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private javax.swing.JRadioButton rbEfectivo;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel tituloCuotas;
    private javax.swing.JLabel tituloInteres;
    private javax.swing.JLabel tituloTotal;
    private javax.swing.JLabel tituloValorCuotas;
    // End of variables declaration//GEN-END:variables
}
