package inventario;

import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fede
 */
public class VistaCatalogo extends javax.swing.JFrame {

  
    public VistaCatalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        botonAtras = new javax.swing.JButton();
        tituloCatalogo = new javax.swing.JLabel();
        panelCentral = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        botonAgregar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 60, 5));

        botonAtras.setText("Atrás");
        panelSuperior.add(botonAtras);

        tituloCatalogo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloCatalogo.setText("       Catálogo");
        panelSuperior.add(tituloCatalogo);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.NORTH);

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelCentral.setViewportView(tablaCatalogo);

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        botonAgregar.setText("Agregar");
        panelInferior.add(botonAgregar);

        botonModificar.setText("Modificar");
        panelInferior.add(botonModificar);

        botonEliminar.setText("Eliminar");
        panelInferior.add(botonEliminar);

        botonFiltrar.setText("Filtrar productos con stock mínimo");
        panelInferior.add(botonFiltrar);

        getContentPane().add(panelInferior, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonFiltrar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JScrollPane panelCentral;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaCatalogo;
    private javax.swing.JLabel tituloCatalogo;
    // End of variables declaration//GEN-END:variables


    private DefaultTableModel modeloTabla;
    private final String[] TITULO_COLUMNAS = {"Código","Descripción", "Stock", "Precio"};
    
    private void crearTabla(Catalogo catalogo) {
        ArrayList<Producto> listaAuxiliar = new ArrayList<>(catalogo.getListaProducto());
        Object[][] datos = new Object[listaAuxiliar.size()][TITULO_COLUMNAS.length];

        for (int i = 0; i < listaAuxiliar.size(); i++) {

            datos[i][0] = listaAuxiliar.get(i).getCodigo();
            datos[i][1] = listaAuxiliar.get(i).getDescripcion();
            datos[i][2] = listaAuxiliar.get(i).getStock();
            datos[i][2] = listaAuxiliar.get(i).getPrecioUnitario();

        }

        modeloTabla = new DefaultTableModel(datos, TITULO_COLUMNAS) {

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        tablaCatalogo.setModel(modeloTabla);
    }

    private void actualizarTabla() {
        LinkedList<Producto> listaAuxiliar = new LinkedList<>(inventario.listaInventario);

        modeloTabla.setRowCount(listaAuxiliar.size());

        for (int i = 0; i < listaAuxiliar.size(); i++) {

            modeloTabla.setValueAt(listaAuxiliar.get(i).getCantidad(), i, 0);
            modeloTabla.setValueAt(listaAuxiliar.get(i).getNombre(), i, 1);
            modeloTabla.setValueAt(listaAuxiliar.get(i).getPrecio(), i, 2);

        }

    }

    /* 
* Este método sirve para comunicarse con el Frame "CrearArticulo", recibir los datos escritos
* por el usuario, añadir un producto a la lista y actualizar la tabla
     */
    public void nuevoArticulo(int cantidad, String nombre, int precio) {

        inventario.añadir(Producto.crearProducto(cantidad, nombre, precio));
        actualizarTabla();

    }

    
    
    private boolean hayFilaSeleccionada() {

        return tablaInventario.isRowSelected(tablaInventario.getSelectedRow());
    }

    private int articuloSeleccionado() {

        if (tablaInventario.getSelectedRows().length <= 1) {
            return tablaInventario.getSelectedRow();
        }
        return -1;
    }



}
